export const ARTICLE_UPDATE = 'ARTICLE_UPDATE';

export const ARTICLE_PAGE = 'ARTICLE_PAGE';

export const ARTICAL_TOTAL_PAGE_UPDATE = 'ARTICAL_TOTAL_PAGE_UPDATE';

export const FETCH_ARTICAL_LOAD = 'FETCH_ARTICAL_LOAD';
