export const ARTICLE_UPDATE = 'ARTICLE_UPDATE';

export const ARTICLE_PAGE = 'ARTICLE_PAGE';

export const ARTICAL_TOTAL_PAGE_UPDATE = 'ARTICAL_TOTAL_PAGE_UPDATE';

export const FETCH_ARTICAL_LOAD = 'FETCH_ARTICAL_LOAD';

export const FETCH_USER_REGISTER = 'FETCH_USER_REGISTER';

export const FETCH_USER_AUTHENTICATION = 'FETCH_USER_AUTHENTICATION';

export const FETCH_USER_REGISTER_ERROR = 'FETCH_USER_REGISTER_ERROR';

export const FETCH_USER_AUTHENTICATION_ERROR =
  'FETCH_USER_AUTHENTICATION_ERROR';

export const FETCH_USER_AUTHORIZED = 'FETCH_USER_AUTHORIZED';

export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_UPDATE = 'USER_UPDATE';

export const ARTICLE_UPDATE_NEW = 'ARTICLE_UPDATE_NEW';

export const ARTICLE_DELETE = 'ARTICLE_DELETE';

export const FETCH_ARTICLE_LIKE_FAVORITE_UPDATE =
  'FETCH_ARTICLE_LIKE_FAVORITE_UPDATE';
